package main

import "fmt"

func main() {
    
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    
    fmt.Println()
    
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    
    fmt.Println()
    
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    fmt.Print("Hello, custom playground")
    
    for i := 0; i < 20; i++ {
        fmt.Println("Hello, custom playground")
    }
}